### Create Region
POST localhost:8080/api/region
Content-Type: application/json

{
  "orderNumber": 5,
  "nameUz": "Andijon",
  "nameRu": "Андижан",
  "nameEn": "Andijan",
  "regionKey": 60
}


### Update Region
PUT localhost:8080/api/region/3
Content-Type: application/json

{
  "regionKey": 61
}


### Delete Region (by id)
DELETE localhost:8080/api/region/2
