### Create Region
POST localhost:8080/api/region
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Salom",
  "nameRu": "Privet",
  "nameEn": "Hello",
  "regionKey": 1
}


### Update Region
PUT localhost:8080/api/region/1
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Toshkent",
  "nameRu": "Ташкент",
  "nameEn": "Tashkent",
  "regionKey": 1
}


### Delete Region (by id)
DELETE localhost:8080/api/region/2
