### Create Region
POST localhost:8080/api/region
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Andijon",
  "nameRu": "Андижан",
  "nameEn": "Andijan",
  "regionKey": 60
}


### Update Region
PUT localhost:8080/api/region/5
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Andijon",
  "nameRu": "Андижан",
  "nameEn": "Andijan",
  "regionKey": 65
}


### Delete Region (by id)
DELETE localhost:8080/api/region/5
